---
bloatware_packages:
  - 1password-beta
  - 1password-cli
  - signal-desktop
  - typora

bloatware_files:
  # 1Password config files
  - "{{ ansible_facts['env']['HOME'] }}/.config/1Password"
  - "{{ ansible_facts['env']['HOME'] }}/.config/chromium/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/google-chrome/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/google-chrome-beta/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/google-chrome-unstable/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/microsoft-edge-dev/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/vivaldi/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.config/vivaldi-snapshot/NativeMessagingHosts/com.1password.1password.json"
  - "{{ ansible_facts['env']['HOME'] }}/.mozilla/native-messaging-hosts/com.1password.1password.json"
  # Basecamp web app
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/Basecamp.desktop"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/icons/Basecamp.png"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/icons/hicolor/48x48/apps/Basecamp.png"
  - "{{ ansible_facts['env']['HOME'] }}/.config/Basecamp"
  - "{{ ansible_facts['env']['HOME'] }}/.cache/Basecamp"
  # Google Contacts web app
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/Google Contacts.desktop"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/icons/Google Contacts.png"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/icons/hicolor/48x48/apps/Google Contacts.png"
  - "{{ ansible_facts['env']['HOME'] }}/.config/Google Contacts"
  - "{{ ansible_facts['env']['HOME'] }}/.cache/Google Contacts"
  # Google Messages web app
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/Google Messages.desktop"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/icons/Google Messages.png"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/icons/hicolor/48x48/apps/Google Messages.png"
  - "{{ ansible_facts['env']['HOME'] }}/.config/Google Messages"
  - "{{ ansible_facts['env']['HOME'] }}/.cache/Google Messages"
  # Google Photos web app
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/Google Photos.desktop"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/icons/Google Photos.png"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/icons/hicolor/48x48/apps/Google Photos.png"
  - "{{ ansible_facts['env']['HOME'] }}/.config/Google Photos"
  - "{{ ansible_facts['env']['HOME'] }}/.cache/Google Photos"
  # HEY web app
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/HEY.desktop"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/icons/HEY.png"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/icons/hicolor/48x48/apps/HEY.png"
  - "{{ ansible_facts['env']['HOME'] }}/.config/HEY"
  - "{{ ansible_facts['env']['HOME'] }}/.cache/HEY"
  # Signal config
  - "{{ ansible_facts['env']['HOME'] }}/.config/Signal"
  # ChatGPT web app
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/ChatGPT.desktop"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/icons/ChatGPT.png"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/icons/hicolor/48x48/apps/ChatGPT.png"
  - "{{ ansible_facts['env']['HOME'] }}/.config/ChatGPT"
  - "{{ ansible_facts['env']['HOME'] }}/.cache/ChatGPT"
  # Typora config
  - "{{ ansible_facts['env']['HOME'] }}/.config/Typora"
  - "{{ ansible_facts['env']['HOME'] }}/.local/share/applications/typora.desktop"
