---
pacman_packages_to_install:
  - python-pipx
  - python-poetry
  - uv
  - plantuml
  - graphviz
  - pandoc
  - texlive-basic
  - texlive-latex
  - texlive-latexrecommended
  - texlive-latexextra
  - texlive-binextra
  - texlive-fontsrecommended
  - texlive-bibtexextra
  - texlive-langitalian
  - biber
  - cmake
  - ninja
  - jdk17-openjdk
  - rsync
  - man-pages
  - lcov
  - flatpak
  - flatpak-builder

aur_packages_to_install:
  - android-sdk
  - android-sdk-build-tools
  - android-sdk-cmdline-tools-latest
  - android-platform
  - android-sdk-platform-tools
  - yed
  - snapd

flatpak_packages_to_install:
  - org.flatpak.Builder

pipx_packages_to_install:
  - mistral-pdf-to-markdown

flutter_install_dir: "/home/{{ ansible_facts['user_id'] }}/development"
flutter_releases_url: "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

android_system_images:
  - "system-images;android-34;google_apis_playstore;x86_64"
